### PR TITLE
Add husky prepush hook

### PR DESCRIPTION
**Pull request by BrendanAnnable**
Automatically runs `yarn tslint` on `git push`. It is fast enough not to be annoying and you can use `--no-verify` to bypass if need.

This would have saved me a few times already since it doesn't error during development with just `yarn start` and only found out when the build failed 😛 

p.s. you can run `yarn tslint:fix` to automatically fix most tslint issues!

### CODE REVIEW

**Comment by BrendanAnnable** [comment]
@Phasedd @JosephusPaye please also approve if this works for you 🙂

**Comment by BrendanAnnable** [comment]
@JosephusPaye ping 🙂

**Comment by JosephusPaye** [comment]
Hey @brendanAnnable, sorry for not responding earlier, been swamped with uni work. 

It think it works for me:



However, should `tslint` also be setup to lint `.tsx` files also? I have to manually run this for actual linting to work for me:

```shell
tslint -c tslint.json 'src/**/*.ts?(x)'
```

**Comment by BrendanAnnable** [comment]
No worries @JosephusPaye — I completely understand!

Great catch regarding `*.tsx`, I'll fix that up.

**Comment by BrendanAnnable** [comment]
Done!

**Comment by JosephusPaye** [comment]
Also it seems like the single quotes doesn't work on Windows (when ran through `yarn` or `npm run`).

**Comment by BrendanAnnable** [comment]
Hmm really? Do you need double quotes?

**Comment by JosephusPaye** [comment]
It works without quotes.

**Comment by BrendanAnnable** [comment]
Without quotes means we're passing off the path globbing to the specific shell of the user. I would have expected no quotes to actually be less consistent across platforms than with quotes... maybe you need to run `yarn` again and make sure you have installed the new dependencies?

**Comment by JosephusPaye** [comment]
I ran `git pull` and then this, with no changes:

**Comment by BrendanAnnable** [comment]
Hmm yep seeing the same issue on my windows VM, double quotes also work but I'll look into it a bit further before settling on anything.

**Comment by BrendanAnnable** [comment]
Switched to use `{,x}` instead of `?(x)` as it was the parenthesis causing the windows issue. Tested on OSX and Windows.

**Comment by BrendanAnnable** [comment]
All good to merge @JosephusPaye? 🙂

**Comment by JosephusPaye** [comment]
All good now.

**Comment by BrendanAnnable** [comment]
Hurray!

**Pull request merged**
