### PR TITLE
Use BuildKite for NUsight2 builds

### PR DESCRIPTION
**Pull request by TrentHouliston**

### CODE REVIEW

**Comment by BrendanAnnable** [comment]
Is buildkite better somehow? 😮

**Comment by TrentHouliston** [comment]
It might be! It at the very least isn’t running on the terrible vms that travis uses. But it’s impossible to know without making a PR so it can try do things. We use it for the NUbots repo and builds went from 40 minutes to 4

**Comment by TrentHouliston** [comment]
It's currently faster than Travis was, however, it's not doing the same caching of node_modules etc. So it could be made even faster in theory if someone wants to look into that in the future. But for now faster is faster.

**Comment by BrendanAnnable** [comment]
Can we keep the slack integration?

**Comment by JosephusPaye** [comment]
Can do: https://buildkite.com/docs/integrations/slack

**Comment by TrentHouliston** [comment]
Slack integration has been done

**Pull request merged**
