### PR TITLE
Add Odometry Visualizer

### PR DESCRIPTION
**Pull request by BrendanAnnable**
The beginnings of a dedicated odometry visualizer tab

Screen Shot 2020-06-29 at 10 08 08 pm

### CODE REVIEW

**Comment by JosephusPaye** [comment]
Looks nice! Could we make the arrow lines thicker?

**Comment by JosephusPaye** [comment]
> Could we get labels for those vectors?

If we can't attach labels directly on the arrows, could be useful having a legend at the bottom.

**Comment by TrentHouliston** [comment]
> Looks nice! Could we make the arrow lines thicker?
> 
> Edit:
> 
> There's a [hacky solution with ArrowHelper](https://stackoverflow.com/a/36298542) which has [caveats](https://discourse.threejs.org/t/changing-linebasicmaterial-in-arrowhelper/3690/2). The alternative is [drawing the line and arrowhead yourself](https://threejs.org/examples/webgl_lines_fat.html).
> 
> Probably not worth the trouble. I just find it a little difficult to see the blue arrow against the dark background. Another color or a brighter blue might help?

We're just going to draw the line and cone ourselves, it's not that hard. Just that for rapid development the ArrowHelper was there and convenient

**Comment by BrendanAnnable** [comment]
Legend added!

Screen Shot 2020-06-30 at 7 31 14 pm

**Pull request merged**
