### PR TITLE
Uninstall unimplemented features

### PR DESCRIPTION
**Pull request by BrendanAnnable**
I think it might be good to uninstall these for now, and then get excited as we see them pop back as they get implemented 🙂

### CODE REVIEW

**Comment by TrentHouliston** [comment]
Not going to also delete the modules themselves? there's not much there anyway

**Comment by BrendanAnnable** [comment]
They have icons and things!

**Comment by BrendanAnnable** [comment]
We should probably delete anything we have no plan to implement in NUsight2, do any of these fall under that category?

**Comment by BrendanAnnable** [comment]
Future component writers, steal the icons from this PR!

**Pull request merged**
